# -*- coding: utf-8 -*-
"""machineLearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-WAXcgmztI7zeaScTTkbE0eCW-mfyWY_

Importando todos os elementos necessários
"""

from sklearn.datasets import load_breast_cancer, load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

"""Atribuindo os datasets às variáveis"""

#base de dados de flores

flor = load_iris() 

#base de dados de câncer de mama

cancer = load_breast_cancer()

"""Conhecendo os dados"""

#classificação dos tipos de flores

print("Classificação dos tipos de flores: ", flor.target_names)
print('\n\n')

#classificação dos tipos de câncer


print("Classificação dos tipos de câncer: ", cancer.target_names)
print('\n\n')

#gabarito dos tipos de flores

print("Gabarito dos tipos de flores: \n", flor.target)
print('\n\n')

#gabarito dos tipos de câncer

print("Gabarito dos tipos de câncer: \n", cancer.target)
print('\n\n')

#parâmetros para avaliação do tipo de flor

print("Parâmetros para avaliação do tipo de flor: \n", flor.feature_names)
print('\n\n')

#parâmetros para avaliação do tipo de câncer

print("Parâmetros para avaliação do tipo de câncer: \n",cancer.feature_names)
print('\n\n')

#dados para classificação das flores

print("Dados para classificação das flores: \n", flor.data)
print('\n\n')

#dados para clasificação do câncer

print("Dados para classificação do câncer: \n", cancer.data)

"""Ajustando os dados para treino e teste"""

#base de flores

F_train, F_test, f_train, f_test = train_test_split(flor.data, flor.target, test_size = 0.3)

#base de câncer

C_train, C_test, c_train, c_test = train_test_split(cancer.data, cancer.target, test_size = 0.3)

"""Atribuindo algoritmos de classificação"""

knn = KNeighborsClassifier()
knn2 = KNeighborsClassifier()

print(knn)

#seleção do número de vizinhos

knn.n_neighbors = 5
knn2.n_neighbors = 5

"""Treinando algoritmo KNN"""

#treino câncer

print(knn.fit(C_train, c_train))

#treino flor

print(knn2.fit(F_train, f_train))

"""Classificação dos resultados"""

#câncer

print('Resultado da base de câncer: ', knn.score(C_test, c_test) * 100, '%')

#flor

print('Resultado da base de flores: ', knn2.score(F_test, f_test) * 100, '%')